# MultiClipboard
# Gitlab CI config
# This is a Maven project, using JUnit and Mockito.

image: maven:maven-javafx

build:
  script:
    mvn -B clean generate-sources compile

test:
  script:
    mvn -B test